In [2]:
import numpy as np 

In [3]:
# 1. Create a NumPy array with values from 1 to 10
arr = np.arange(1, 11)
print("Array:", arr)

Array: [ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# 2. Create a 3x3 matrix with values ranging from 1 to 9
matrix = np.arange(1, 10).reshape(3, 3)
print("3x3 Matrix:\n", matrix)

3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# 3. Generate an array of 5 random numbers between 0 and 1
rand_arr = np.random.rand(5)
print("Random Array:", rand_arr)

Random Array: [0.59878918 0.77823741 0.48419612 0.82238514 0.47392362]


In [6]:
# 4. Create a 4x4 identity matrix
identity_matrix = np.eye(4)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
# 5. Find the mean and standard deviation of an array
data = np.array([10, 20, 30, 40, 50])
print("Mean:", np.mean(data))
print("Standard Deviation:", np.std(data))

Mean: 30.0
Standard Deviation: 14.142135623730951


In [8]:
# 6. Perform element-wise addition, subtraction, multiplication, and division
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [9]:
# 7. Find the dot product of two arrays
dot_product = np.dot(arr1, arr2)
print("Dot Product:", dot_product)


Dot Product: 32


In [10]:
# 8. Find the transpose of a matrix
transpose_matrix = np.transpose(matrix)
print("Transposed Matrix:\n", transpose_matrix)


Transposed Matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
# 9. Extract elements greater than a certain value
filtered_arr = arr[arr > 5]
print("Elements greater than 5:", filtered_arr)

Elements greater than 5: [ 6  7  8  9 10]


In [12]:
# 10. Replace all even numbers in an array with -1
arr[arr % 2 == 0] = -1
print("Modified Array:", arr)

Modified Array: [ 1 -1  3 -1  5 -1  7 -1  9 -1]
